### PR TITLE
Update TC4 - Aspects.zs

### PR DESCRIPTION
**Pull request by daforsyth**
Feel free to edit as much as desired.
Adds aspects to:

- Ars Magia
- Blood Magic
- Electrobobs
- Extra utilities
- Mekanism
- MineFactory Reloaded
- Modular Power Suits
- Open Blocks
- Thaumcraft & Addons
- Thermal Expansion
- Tinkers Construct
- Some vanilla Minecraft items

### CODE REVIEW

**Comment by daforsyth** [comment]
Some things to note most aspects added I consider responsible
In particular, I'd look at Ars Magica boss drops have a rather high aspect count
Check if vanilla item tweaks is acceptable

On my end, I've ran this script without problems in single player, but always test. I'm assuming you've done custom stuff to some of these mods so not every item in the respective mod is covered. (Clay patterns from TiCon come to mind)

**Comment by DrParadox7** [comment]
@daforsyth One of the new additions throws `NullPointExceptions` (without crashing, but it still shows on logs), which means there are attempts of aspects being added to items or creatures that do not exist (much like https://github.com/DrParadox7/Lost-Era-Modpack/commit/bafc002ac81b11b936f874abb79fa778f1f0eee4).

**Comment by daforsyth** [comment]
Will look into it and aim to deliver a version without `NullPointExceptions` in the near future

**Comment by daforsyth** [comment]
> @daforsyth One of the new additions throws `NullPointExceptions` (without crashing, but it still shows on logs), which means there are attempts of aspects being added to items or creatures that do not exist (much like [bafc002](https://github.com/DrParadox7/Lost-Era-Modpack/commit/bafc002ac81b11b936f874abb79fa778f1f0eee4)).

Able to tell me where to look to see the `NullPointExceptions` being thrown? I ran Mojang's log and couldn't find the error code when using the built-in search feature after running a ./mt reload. Also checked the minetweaker logs and navigated via comments and couldn't find the exceptions being thrown.

I don't doubt the exception is being thrown, but I am unexperienced at knowing what to look at.

**Comment by DrParadox7** [comment]
> > @daforsyth One of the new additions throws `NullPointExceptions` (without crashing, but it still shows on logs), which means there are attempts of aspects being added to items or creatures that do not exist (much like [bafc002](https://github.com/DrParadox7/Lost-Era-Modpack/commit/bafc002ac81b11b936f874abb79fa778f1f0eee4)).
> 
> Able to tell me where to look to see the `NullPointExceptions` being thrown? I ran Mojang's log and couldn't find the error code when using the built-in search feature after running a ./mt reload. Also checked the minetweaker logs and navigated via comments and couldn't find the exceptions being thrown.
> 
> I don't doubt the exception is being thrown, but I am unexperienced at knowing what to look at.

Sure, no problem. 
The logs are found in `[Instance_Name]\.minecraft\logs\fml-client-latest.log` and the error occurs on world load.

The easy way to debug this is to first remove the addition of the script and then slowly add the missing parts until the NPE pops up.
You don't have to restart the game each time, you can just use the command `/mt reload` to load the scripts additions each time.

**Comment by daforsyth** [comment]
[latest.log](https://github.com/DrParadox7/Lost-Era-Modpack/files/15331026/latest.log)

Having a hard time replicating `NullPointerException` that correlates to my editions. Attached is my latest.log

How I went around testing:
1. I grabbed the file `TC4 - Aspects.zs` from the main branch (Replaced current file with this one)
2. Loaded single player world
3. Typed in chat, then ran a `/mt reload`
4. Searched for typed messages, then searched for `NullPointer` under that

Here are my messages in the logs:
**TEST START**
- First loading in the world. Have an unedited `TC4 - Aspects.zs` from main branch
- A `NullPointer` seems to occur before this message is typed. ie in the loading of the world

**TEST1**
- added my editions to the file `TC4 - Aspects.zs`
- ran `/mt reload`
- encountered: `.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException`

**TEST2**
- Removed additions
- ran `/mt reload`
- No `NullPointerException` thrown

**TEST3**
- Readded additions
- ran `/mt reload`
- No `NullPointerException` thrown

So from what I'm seeing, an unedited script throws the `NullPointerException` at the loading of a world
Another `NullPointerException` is thrown after the first `/mt reload is ran`
Any other changes followed with a `/mt reload` does not throw a `NullPointerException`

TDLR:
`NullPointerException` seems to be thrown regardless of my edits of `TC4 - Aspects.zs` the first time a world is loaded, and after the first time a `/mt reload` is run. These two `NullPointerException`'s occur with or without my editions. I cannot make it throw a `NullPointerException` after those two are thrown regardless of my edits being included or excluded.

**Comment by DrParadox7** [comment]
Seems that's the case. I'll add that to the things to fix

**Pull request merged**
